"use client"
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/scene.gltf -o ./src/components/car.tsx -ts 
Author: ᗩᒪE᙭. Kᗩ.🚗 (https://sketchfab.com/Alex.Ka.)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/mclaren-f1-1993-nfs2-edition-scene-version-49502d9e4874458aa6223222a56ff0b7
Title: McLaren F1 1993 NFS2 Edition. Scene Version
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_11: THREE.Mesh
    Object_12: THREE.Mesh
    Object_13: THREE.Mesh
    Object_14: THREE.Mesh
    Object_15: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_21: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_25: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_29: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_39: THREE.Mesh
    Object_40: THREE.Mesh
    Object_41: THREE.Mesh
    Object_42: THREE.Mesh
    Object_43: THREE.Mesh
    Object_44: THREE.Mesh
    Object_45: THREE.Mesh
    Object_46: THREE.Mesh
    Object_47: THREE.Mesh
    Object_48: THREE.Mesh
    Object_49: THREE.Mesh
    Object_50: THREE.Mesh
    Object_51: THREE.Mesh
    Object_52: THREE.Mesh
    Object_53: THREE.Mesh
    Object_54: THREE.Mesh
    Object_55: THREE.Mesh
    Object_56: THREE.Mesh
    Object_57: THREE.Mesh
    Object_58: THREE.Mesh
    Object_59: THREE.Mesh
  }
  materials: {
    Brembo_supportlogo: THREE.MeshStandardMaterial
    F1_front_plastic: THREE.MeshStandardMaterial
    F1_nip_logo: THREE.MeshPhysicalMaterial
    F1_red_F: THREE.MeshStandardMaterial
    F1_red_R: THREE.MeshStandardMaterial
    F1_side: THREE.MeshPhysicalMaterial
    McLaren_F1_1993_By_Alex_Ka: THREE.MeshPhysicalMaterial
    McLaren_logo: THREE.MeshPhysicalMaterial
    Rear_grill: THREE.MeshPhysicalMaterial
    Smoke: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    black_aluminium: THREE.MeshStandardMaterial
    black_chrome: THREE.MeshStandardMaterial
    black_chrome2: THREE.MeshPhysicalMaterial
    black_matte: THREE.MeshStandardMaterial
    black_plastic: THREE.MeshPhysicalMaterial
    bottom: THREE.MeshStandardMaterial
    brakedisk: THREE.MeshStandardMaterial
    brakelight: THREE.MeshPhysicalMaterial
    bronze: THREE.MeshStandardMaterial
    chrome: THREE.MeshStandardMaterial
    chrome2: THREE.MeshStandardMaterial
    door_stitch: THREE.MeshStandardMaterial
    engine: THREE.MeshStandardMaterial
    exhaust: THREE.MeshPhysicalMaterial
    exhaust_gold: THREE.MeshStandardMaterial
    exhaust_hole: THREE.MeshStandardMaterial
    exhaust_metal_circles: THREE.MeshStandardMaterial
    floor: THREE.MeshPhysicalMaterial
    front_turn_signal: THREE.MeshStandardMaterial
    fuel_clap: THREE.MeshStandardMaterial
    grill1: THREE.MeshStandardMaterial
    grill2: THREE.MeshStandardMaterial
    grill_3: THREE.MeshStandardMaterial
    grill_f: THREE.MeshStandardMaterial
    grill_side: THREE.MeshStandardMaterial
    headlight_1: THREE.MeshPhysicalMaterial
    headlight_2: THREE.MeshPhysicalMaterial
    headlightglass: THREE.MeshPhysicalMaterial
    interior: THREE.MeshStandardMaterial
    mirrors: THREE.MeshStandardMaterial
    material_41: THREE.MeshStandardMaterial
    material_42: THREE.MeshPhysicalMaterial
    plate_F: THREE.MeshStandardMaterial
    plate_R: THREE.MeshStandardMaterial
    rear_lamp: THREE.MeshPhysicalMaterial
    rear_turn_signal: THREE.MeshPhysicalMaterial
    material_47: THREE.MeshPhysicalMaterial
    rimbolt: THREE.MeshStandardMaterial
    rimlogo: THREE.MeshPhysicalMaterial
    side_turn_signal: THREE.MeshPhysicalMaterial
    suport1: THREE.MeshPhysicalMaterial
    suport2: THREE.MeshPhysicalMaterial
    tire: THREE.MeshStandardMaterial
    tire_side: THREE.MeshStandardMaterial
    windo_F: THREE.MeshPhysicalMaterial
    windo_R: THREE.MeshPhysicalMaterial
    windo_S: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0.04, 0]} scale={1.053}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.Brembo_supportlogo} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials.F1_front_plastic} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.F1_nip_logo} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.F1_red_F} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.F1_red_R} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.F1_side} />
        <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials.McLaren_F1_1993_By_Alex_Ka} />
        <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials.McLaren_logo} />
        <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.Rear_grill} />
        {/* <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.Smoke} /> */}
        <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.material} />
        <mesh castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials.black_aluminium} />
        <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials.black_chrome} />
        <mesh castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials.black_chrome2} />
        <mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials.black_matte} />
        <mesh castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials.black_plastic} />
        <mesh castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials.bottom} />
        <mesh castShadow receiveShadow geometry={nodes.Object_19.geometry} material={materials.brakedisk} />
        <mesh castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials.brakelight} />
        <mesh castShadow receiveShadow geometry={nodes.Object_21.geometry} material={materials.bronze} />
        <mesh castShadow receiveShadow geometry={nodes.Object_22.geometry} material={materials.chrome} />
        <mesh castShadow receiveShadow geometry={nodes.Object_23.geometry} material={materials.chrome2} />
        <mesh castShadow receiveShadow geometry={nodes.Object_24.geometry} material={materials.door_stitch} />
        <mesh castShadow receiveShadow geometry={nodes.Object_25.geometry} material={materials.engine} />
        <mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={materials.exhaust} />
        <mesh castShadow receiveShadow geometry={nodes.Object_27.geometry} material={materials.exhaust_gold} />
        <mesh castShadow receiveShadow geometry={nodes.Object_28.geometry} material={materials.exhaust_hole} />
        <mesh castShadow receiveShadow geometry={nodes.Object_29.geometry} material={materials.exhaust_metal_circles} />
        <mesh castShadow receiveShadow geometry={nodes.Object_30.geometry} material={materials.floor} scale={[10,10,1]} />
        <mesh castShadow receiveShadow geometry={nodes.Object_31.geometry} material={materials.front_turn_signal} />
        <mesh castShadow receiveShadow geometry={nodes.Object_32.geometry} material={materials.fuel_clap} />
        <mesh castShadow receiveShadow geometry={nodes.Object_33.geometry} material={materials.grill1} />
        <mesh castShadow receiveShadow geometry={nodes.Object_34.geometry} material={materials.grill2} />
        <mesh castShadow receiveShadow geometry={nodes.Object_35.geometry} material={materials.grill_3} />
        <mesh castShadow receiveShadow geometry={nodes.Object_36.geometry} material={materials.grill_f} />
        <mesh castShadow receiveShadow geometry={nodes.Object_37.geometry} material={materials.grill_side} />
        <mesh castShadow receiveShadow geometry={nodes.Object_38.geometry} material={materials.headlight_1} />
        <mesh castShadow receiveShadow geometry={nodes.Object_39.geometry} material={materials.headlight_2} />
        <mesh castShadow receiveShadow geometry={nodes.Object_40.geometry} material={materials.headlightglass} />
        <mesh castShadow receiveShadow geometry={nodes.Object_41.geometry} material={materials.interior} />
        <mesh castShadow receiveShadow geometry={nodes.Object_42.geometry} material={materials.mirrors} />
        <mesh castShadow receiveShadow geometry={nodes.Object_43.geometry} material={materials.material_41} />
        <mesh castShadow receiveShadow geometry={nodes.Object_44.geometry} material={materials.material_42} />
        <mesh castShadow receiveShadow geometry={nodes.Object_45.geometry} material={materials.plate_F} />
        <mesh castShadow receiveShadow geometry={nodes.Object_46.geometry} material={materials.plate_R} />
        <mesh castShadow receiveShadow geometry={nodes.Object_47.geometry} material={materials.rear_lamp} />
        <mesh castShadow receiveShadow geometry={nodes.Object_48.geometry} material={materials.rear_turn_signal} />
        <mesh castShadow receiveShadow geometry={nodes.Object_49.geometry} material={materials.material_47} />
        <mesh castShadow receiveShadow geometry={nodes.Object_50.geometry} material={materials.rimbolt} />
        <mesh castShadow receiveShadow geometry={nodes.Object_51.geometry} material={materials.rimlogo} />
        <mesh castShadow receiveShadow geometry={nodes.Object_52.geometry} material={materials.side_turn_signal} />
        <mesh castShadow receiveShadow geometry={nodes.Object_53.geometry} material={materials.suport1} />
        <mesh castShadow receiveShadow geometry={nodes.Object_54.geometry} material={materials.suport2} />
        <mesh castShadow receiveShadow geometry={nodes.Object_55.geometry} material={materials.tire} />
        <mesh castShadow receiveShadow geometry={nodes.Object_56.geometry} material={materials.tire_side} />
        <mesh castShadow receiveShadow geometry={nodes.Object_57.geometry} material={materials.windo_F} />
        <mesh castShadow receiveShadow geometry={nodes.Object_58.geometry} material={materials.windo_R} />
        <mesh castShadow receiveShadow geometry={nodes.Object_59.geometry} material={materials.windo_S} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
